### ISSUE TITLE
Terminal names don't get auto-updated when name changes

### ISSUE THREAD

**Issue by grandrew** [Noctarya/vscode-terminals#1]
Terminal names do update automatically in the "drop-down" list in vscode terminal when for example process finishes there (in the background, even when this particular terminal is not active and you're on other terminal)

terminal-statusbar aims to show terminal names, but they don't get updated automatically when name changes

**Comment by grandrew** [comment]
Proposed solution:

- [ ] Create a `setInterval` timer to call `refreshTerminalItems()` every configured-number-seconds (default to `5`)
- [ ] Clear & run the timer in `refreshTerminalItems()` at each call to make if fail-proof

**Comment by Noctarya** [comment]
Thank you for reporting this bug and give the proposed solution.

I added a corresponding configuration parameter and let the name of each terminal updated for itself. If I called `refreshTerminalItems()` after the interval, there would be an ugly flickering, because the icons are created and exchanged every time.

The fix is contained in version 0.3.1.
