### ISSUE TITLE
Highlight current terminal

### ISSUE THREAD

**Issue by grandrew** [Noctarya/vscode-terminals#2]
I would like to propose the feature to highlight current open terminal, if it is present in the terminals list in status bar. Most obvious way is to just have the text in bold, or maybe have the terminal icon in inverse color.

This would probably require

- [ ] finding how to attach to terminal change event
- [ ] finding way to get what terminal is currently open

**Comment by Noctarya** [comment]
In the next release there will be the possibility to highlight the active terminal.
In the current state of development, it is already possible to highlight the active terminal in color. A fixed color is currently used as default.

So far I have unfortunately not found a way to solve the following problems:
- [ ] to highlight the text in bold
- [ ] to query the current background color of the status bar
- [ ] there is a slight delay when a new terminal is opened.

**Comment by Noctarya** [comment]
Since version 0.4.0 from 02/17/2020, the active terminal is highlighted in color in the status bar. Additional highlighting with bold text is not possible with the api of vscode.

By default, the color depends on the chosen theme. It is also possible to define your own colors for the active terminal and for inactive terminals in the status bar. The following theming parameters exist for this:
* extendedTerminalIntegration.statusBar.activeForeground
* extendedTerminalIntegration.statusBar.foreground
